### ISSUE TITLE
Privacy Manager does not clean all data from chromium.

### ISSUE THREAD

**Issue by Gomam0n-afk** [Privacy-Managers/Privacy-Manager#93]
Hello, i've been using Privacy Manager for some time but i discovered it does not delete all the history and data from the browser, the browser keeps a few entries i've accessed before closing and restarting chrome. all the options for clear on startup are on yet it fails to clear some of the history and i have to do it myself manually.

I'm using Ungoogled-chromium if that matters, latest version from chocolatey.

**Comment by Manvel** [comment]
Hello @Gomam0n-afk 

Thanks for the request.

Please note that Privacy Manager is using [unprotectedWeb](https://developer.chrome.com/docs/extensions/reference/browsingData/#origin-types) as data deletion flag, which prevent users from deleting by mistake data that is set by `hosted apps and extensions`, there is an [issue about making that more clear](https://github.com/Privacy-Managers/Privacy-Manager/issues/14), but unfortunately I didn't get my hands on that clarification in UI.

If the "undeleted" data you mention doesn't fall under the `unprotectedWeb` flag deletion scope, please let me know if you can provide reproduction steps, so I can reproduce and help with fixing the issue.

Thanks,
Manvel

**Comment by Gomam0n-afk** [comment]
> Hello @Gomam0n-afk
> 
> Thanks for the request.
> 
> Please note that Privacy Manager is using [unprotectedWeb](https://developer.chrome.com/docs/extensions/reference/browsingData/#origin-types) as data deletion flag, which prevent users from deleting by mistake data that is set by `hosted apps and extensions`, there is an [issue about making that more clear](https://github.com/Privacy-Managers/Privacy-Manager/issues/14), but unfortunately I didn't get my hands on that clarification in UI.
> 
> If the "undeleted" data you mention doesn't fall under the `unprotectedWeb` flag deletion scope, please let me know if you can provide reproduction steps, so I can reproduce and help with fixing the issue.
> 
> Thanks,
> Manvel

The only thing i know is that sometimes when accessing websites, does not delete the entries made in the history (history is said to be empty, but the URL is still appearing when you start to type for it, i have to manually re-clean it in order to get rid of it.)

**Comment by Manvel** [comment]
@Gomam0n-afk I did try to reproduce your issue both on Latest stable Chrome and ungoogled-chrome, but unfortunately I wasn't able to reproduce it. [Here you can find the reproduction using ungoogled-chrome on Windows machine](https://youtu.be/nIOuQo-i888).

Also please try ensuring that no extensions, apps on your browser, or programs on your machine add those records(ex.: By running those pages in the background on start).

**Comment by Manvel** [comment]
Closing this issue for now, feel free to reopen it if [assumptions mentioned in previous comment](https://github.com/Privacy-Managers/Privacy-Manager/issues/93#issuecomment-743736571) are not the case and there is no 3-rd party causing issue.
